# Generated by Django 4.0.4 on 2023-03-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_pipehighpressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipehighpressure',
            name='k_welding',
            field=models.FloatField(choices=[(1, 'Безшовна'), (0.6, 'Електрозварювальна')], default=1, max_length=40),
        ),
    ]
